### PR TITLE
Fix #6701: disable QR Pairing for China

### LINKED ISSUE #6701: QR Pairing in China doesn't work
It appears to be a server misconfiguration: https://bugzilla.mozilla.org/show_bug.cgi?id=1641188

This would block release, so we need to know when it will be fixed.

### PR DESCRIPTION
**Pull request by garvankeeley**

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -2116,7 +2116,10 @@ extension BrowserViewController {
                 parentType = .settings
                 object = .settings
             }
-            let signInVC = FirefoxAccountSignInViewController(profile: profile, parentType: parentType)
+
+            let signInVC = AppInfo.isChinaEdition ?
```
Comment (nbhasin2) [inline Client/Frontend/Browser/BrowserViewController.swift:2120]: Library Panel

File: Client/Frontend/Settings/AppSettingsOptions.swift [hunk 2]
```diff
@@ -46,7 +46,9 @@ class ConnectSetting: WithoutAccountSetting {
     override var accessibilityIdentifier: String? { return "SignInToSync" }
 
     override func onClick(_ navigationController: UINavigationController?) {
-        let viewController = FirefoxAccountSignInViewController(profile: profile, parentType: .settings)
+        let viewController = AppInfo.isChinaEdition ?
```
Comment (nbhasin2) [inline Client/Frontend/Settings/AppSettingsOptions.swift:49]: - Settings menu (Sign in to sync)

**Comment by garvankeeley** [comment]
Uplifted to v26.x branch
