### PR TITLE
Bugfix FXIOS-11702 [v105] Fix `syncClientsThenTabs` function

### LINKED ISSUE #11702: Fix "Sync Now" tabs syncing in the Remote Tab Panel
At the moment, clicking "Sync Now" from the Remote Tab Panel only syncs devices. This is due to a regression in the `syncClientsThenTabs` function that was introduced with the A-S tabs integration work for v103. The "Sync Now" functionality off of the Settings menu and timed syncing are functioning as expected.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4816)

### PR DESCRIPTION
**Pull request by lougeniaC64**
This fixes #11702 which is a regression in the `syncClientsThenTabs` function which is triggered by clicking the "Sync Now" button on the Remote Tabs Panel.

### CODE REVIEW

**Comment by lougeniaC64** [comment]
@nbhasin2 This is the tabs syncing bug we discussed. Just to reiterate for posterity, the bug that was introduced in v103 prevented tabs from being synced after the "Sync Now" button was clicked in the remote tabs panel. Because full syncs were unaffected (timed syncs, clicking "Sync Now" from the settings menu, etc.) this issue was masked and might seem like a delay in tabs syncing to the user.

File: Providers/Profile.swift [hunk 1]
```diff
@@ -1430,8 +1430,14 @@ open class BrowserProfile: Profile {
...
-            return self.sync("clients", function: self.syncClientsWithDelegate)
-            >>> { self.sync("tabs", function: self.syncTabsWithDelegate) }
+            return self.syncSeveral(
+                why: .user,
+                synchronizers:
+                ("clients", self.syncClientsWithDelegate),
+                ("tabs", self.syncTabsWithDelegate)) >>== { statuses in
+                let status = statuses.find { "tabs" == $0.0 }
+                return deferMaybe(status!.1)
+            }
```
Comment (nbhasin2) [inline Providers/Profile.swift:1440]: nit: Indentation

I will look odd on github but its more readable on the XCode side

```suggestion
            return self.syncSeveral(why: .user, synchronizers: ("clients", self.syncClientsWithDelegate),
                                                                                              ("tabs", self.syncTabsWithDelegate)) >>== {
                statuses in
                let status = statuses.find { "tabs" == $0.0 }
                return deferMaybe(status!.1)
            }
```

Comment (lougeniaC64) [reply Providers/Profile.swift:1440]: I think it might be something like this because your first line will be too long.

```
            return self.syncSeveral(
                why: .user,
                synchronizers:
                ("clients", self.syncClientsWithDelegate),
                ("tabs", self.syncTabsWithDelegate)
            ) >>== { statuses in
                let status = statuses.find { "tabs" == $0.0 }
                return deferMaybe(status!.1)
            }
```

File: Providers/Profile.swift [hunk 2]
```diff
@@ -1430,8 +1430,14 @@ open class BrowserProfile: Profile {
...
         public func syncClientsThenTabs() -> SyncResult {
-            return self.sync("clients", function: self.syncClientsWithDelegate)
-            >>> { self.sync("tabs", function: self.syncTabsWithDelegate) }
+            return self.syncSeveral(
+                why: .user,
+                synchronizers:
+                ("clients", self.syncClientsWithDelegate),
+                ("tabs", self.syncTabsWithDelegate)) >>== { statuses in
+                let status = statuses.find { "tabs" == $0.0 }
+                return deferMaybe(status!.1)
```
Comment (nbhasin2) [inline Providers/Profile.swift:1439]: It would be good to write a comment to further explain what this does.

**Review by nbhasin2 — APPROVED** [review]

File: Providers/Profile.swift (hunk 1 above)
Comment (nbhasin2) [reply Providers/Profile.swift:1440]: yeah, that makes sense I just quickly typed on github and likely made it worse ha

**Comment by lmarceau** [comment]
Bitrise build failed due to the following error

Screen Shot 2022-08-24 at 1 11 42 PM

**Comment by nbhasin2** [comment]
> [Bitrise build](https://app.bitrise.io/build/7acb4494-0298-4e97-8a90-0246dc608e2a) failed due to the following error
> 
> Screen Shot 2022-08-24 at 1 11 42 PM

Seems like a BR issue, a quick re-run should fix this 🤞🏼

**Comment by lmarceau** [comment]
[All green now](https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/e915680a-942f-4ad2-952c-507e0cbc3375) 🎉
Screen Shot 2022-08-24 at 1 50 57 PM
