### PR TITLE
 Fix #4780 - Fix and remove obsolete bookmarks tests

### LINKED ISSUE #4780: Fix and remove obsolete bookmarks tests
Before we can land the `rust-bookmarks` branch on `master`, we will need to fix and remove old tests.

### PR DESCRIPTION
**Pull request by justindarc**
This is based on another PR that I'm waiting for review on. Just take a look at the one commit that fixes the tests.

### CODE REVIEW

File: StorageTests/TestSQLiteHistory.swift [hunk 1]
```diff
@@ -662,10 +662,10 @@ class BrowserSchemaV10: BaseHistoricalBrowserSchema {
...
         let args: Args = [
             root, BookmarkRoots.RootGUID, type, "Root", root,
-            BookmarkRoots.MobileID, BookmarkRoots.MobileFolderGUID, type, titleMobile, root,
-            BookmarkRoots.MenuID, BookmarkRoots.MenuFolderGUID, type, titleMenu, root,
-            BookmarkRoots.ToolbarID, BookmarkRoots.ToolbarFolderGUID, type, titleToolbar, root,
-            BookmarkRoots.UnfiledID, BookmarkRoots.UnfiledFolderGUID, type, titleUnsorted, root,
+            1, BookmarkRoots.MobileFolderGUID, type, titleMobile, root,
+            2, BookmarkRoots.MenuFolderGUID, type, titleMenu, root,
+            3, BookmarkRoots.ToolbarFolderGUID, type, titleToolbar, root,
+            4, BookmarkRoots.UnfiledFolderGUID, type, titleUnsorted, root,
```
Comment (garvankeeley) [inline StorageTests/TestSQLiteHistory.swift]: nit: this code is repeated a lot! Is existing/old code though, not sure this is the time to fix it.
