### PR TITLE
Bugfix #9863: "Send to Device" option from the Tab Peek menu doesn't work

### LINKED ISSUE #9863: "Send to Device" option from the Tab Peek menu doesn't work
v97.0 (7635)
iPhone 12 Pro (15.2.1)

1. Long press on a tab in tabs tray.
2. Press on "Send to Device"

Expected: The Share sheet should open (based on the corresponding icon).

Actual: Tab peek is dismissed but nothing else happens after that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3676)

### PR DESCRIPTION
**Pull request by q2r5**
Issue #9863.

This was failing to work as it was trying to have the `BrowserViewController` present the device picker while it was also presenting the tab tray.

### CODE REVIEW

File: Client/Frontend/Browser/GridTabViewController.swift [hunk 1]
```diff
@@ -512,7 +512,7 @@ extension GridTabViewController: TabPeekDelegate {
     }
 
     func tabPeekRequestsPresentationOf(_ viewController: UIViewController) {
-        delegate?.tabTrayRequestsPresentationOf(viewController)
```
Comment (lmarceau) [inline Client/Frontend/Browser/GridTabViewController.swift:515]: Nit: It looks we could entirely remove `tabTrayRequestsPresentationOf` from the delegate.

**Review by lmarceau — APPROVED** [review]
Thanks @q2r5 !
