### PR TITLE
For #8098 - Fix Sync Integ Tests

### LINKED ISSUE #8098: FXIOS-1564 ⁃ [Sync Int Tests] Update device name an navigation to Account Settings
There are two things we need to modify to have [Sync Int Tests](https://github.com/mozilla-mobile/firefox-ios/tree/main/SyncIntegrationTests)working on MacStadium: 
1 - Since there is a new option in Settings, in the first place of the list. This is being clicked in the tests instead of going to the Firefox Account option:
Captura de pantalla 2021-03-09 a las 10 48 09
These to lines have to change due to that to element 1 and 2 accordingly for the `testFxASyncTabs` test:
https://github.com/mozilla-mobile/firefox-ios/blob/main/XCUITests/IntegrationTests.swift#L100
https://github.com/mozilla-mobile/firefox-ios/blob/main/XCUITests/IntegrationTests.swift#L106

And for the `testFxADisconnectConnect` test:
https://github.com/mozilla-mobile/firefox-ios/blob/main/XCUITests/IntegrationTests.swift#L199

2 - The device name is different now: https://github.com/mozilla-mobile/firefox-ios/blob/main/XCUITests/IntegrationTests.swift#L102. Instead of `"Fennec (synctesting) on iOS"` it is: `"Fennec (administrator) on iOS"`
Change also needed in the [test_tabs.js](https://github.com/mozilla-mobile/firefox-ios/blob/main/SyncIntegrationTests/test_tabs.js#L17) file

With those two changes tests will work again ✅

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1564)

### PR DESCRIPTION
**Pull request by AaronMT**
Closes #8098

### CODE REVIEW

File: XCUITests/IntegrationTests.swift [hunk 1]
```diff
@@ -97,13 +97,13 @@ class IntegrationTests: BaseTestCase {
         navigator.nowAt(BrowserTab)
         // This is only to check that the device's name changed
         navigator.goto(SettingsScreen)
-        app.tables.cells.element(boundBy: 0).tap()
+        app.tables.cells.element(boundBy: 1).tap()
```
Comment (isabelrios) [inline XCUITests/IntegrationTests.swift:100]: We need this change below in L#199 too.

**Review by isabelrios — APPROVED** [review]
LGTM, only one more fix to have all tests working again

File: XCUITests/IntegrationTests.swift (hunk 1 above)
Comment (AaronMT) [reply XCUITests/IntegrationTests.swift:100]: Added
