### PR TITLE
Fix #4700: Reader view should switch to a darker theme when using Night mode

### LINKED ISSUE #4700: Reader view should switch to a darker theme when using Night Mode
From https://bugzilla.mozilla.org/show_bug.cgi?id=1415109

Build: 10.0 (7617)
Device: iPad mini 4
iOS: 11.1

Steps to reproduce:
1. Go to bbc.com
2. Open the menu and turn "Night Mode" On
3. Open an article
4. Tap on the Reader View icon

Actual results:
- The content in Reader View is bright as the default theme is "Light".

Suggested solution:
- When using Night Mode we should use as default the "Dark" theme in Reader View.

### PR DESCRIPTION
**Pull request by nick130586**
Fixes #4700

This is the 2nd attempt to fix the issue. The latest commit makes sure we switch back to sepia when switching off dark mode in case sepia was used before. Description from the previous PR:

"In this PR, any reader theme is overridden by the app-wide theme. When Reader mode is opened or app theme is changed, reader's theme will be matched to app's theme.

It's still possible to use any reader theme by setting the desired one, but it will be overridden next time we open Reader mode or change app-wide theme".

Untitled1

### CODE REVIEW

File: Client/Frontend/Reader/ReaderMode.swift [hunk 1]
```diff
@@ -29,6 +29,43 @@ enum ReaderModeTheme: String {
...
+}
+
+extension ReaderModeTheme {
+    func preferredTheme(for theme: ReaderModeTheme? = nil) -> ReaderModeTheme {
+        let theme = theme ?? self
+        let appWideTheme = ReaderModeTheme(rawValue: ThemeManager.instance.currentName.rawValue) ?? .light
+        
+        if appWideTheme.isThemeDark {
+            return .dark // app-wide dark overrides all
+        } else if appWideTheme.isThemeSystemCompatible && theme.isThemeSystemCompatible {
```
Comment (dnarcese) [inline Client/Frontend/Reader/ReaderMode.swift]: A simpler way to write this if statement is `theme != .sepia`. The `appWideTheme` will always be system compatible and the only other condition is that the theme is not sepia.

**Comment by nick130586** [comment]
Thanks for the feedback! Pushed an update.

File: Client/Frontend/Reader/ReaderMode.swift [hunk 2]
```diff
@@ -29,6 +29,25 @@ enum ReaderModeTheme: String {
...
+        let appWideTheme = ReaderModeTheme(rawValue: ThemeManager.instance.currentName.rawValue) ?? .light
+        
+        if appWideTheme == .dark {
+            return .dark // app-wide dark overrides all
+        } else if theme != .sepia {
+            return .light
+        }
+
+        return .sepia
+    }
```
Comment (nbhasin2) [inline Client/Frontend/Reader/ReaderMode.swift]: Hi @nick130586, thanks for submitting the PR for the issue. I think the overall approach is good but we can make it even better by adding few comments and cleanup. We don't really need an extension and an init(). We can easily clean this up by using static function. What do you think? 

Eg. 
```Swift

enum ReaderModeTheme: String {
    case light = "light"
    case dark = "dark"
    case sepia = "sepia"
    
    static func preferredTheme(for theme: ReaderModeTheme? = nil) -> ReaderModeTheme {
        // If there is no reader theme provided than we default to light theme
        let readerTheme = theme ?? .light
        // Get current Firefox theme (Dark vs Normal)
        // Normal means light theme. This is the overall theme used
        // by Firefox iOS app
        let appWideTheme = ThemeManager.instance.currentName
        // We check for 3 basic themes we have Light / Dark / Sepia
        // Theme: Dark - app-wide dark overrides all
        if appWideTheme == .dark {
            return .dark
        // Theme: Sepia - special case for when the theme is sepia.
        // For this we only check the them supplied and not the app wide theme
        } else if readerTheme == .sepia {
            return .sepia
        }
        // Theme: Light - Default case for when there is no theme supplied i.e. nil and we revert to light
        return readerTheme
    }
} 

```

File: Client/Frontend/Reader/ReaderModeStyleViewController.swift [hunk 3]
```diff
@@ -29,7 +29,20 @@ private struct ReaderModeStyleViewControllerUX {
...
+                                       didConfigureStyle style: ReaderModeStyle,
+                                       isUsingUserDefinedColor: Bool)
+}
+
+extension ReaderModeStyleViewControllerDelegate {
+    // Can't use default values in protocols, using chained method calls instead
+    func readerModeStyleViewController(_ readerModeStyleViewController: ReaderModeStyleViewController, 
+                                       didConfigureStyle style: ReaderModeStyle) {
+        self.readerModeStyleViewController(readerModeStyleViewController, didConfigureStyle: style, isUsingUserDefinedColor: false)
+    }
```
Comment (nbhasin2) [inline Client/Frontend/Reader/ReaderModeStyleViewController.swift]: Instead of chaining like you mentioned `Can't use default values in protocols` we should just use your new method. This will look more like: 

```Swift
// Todo: Add a comment explaining that we should keep default value of is as false 
protocol ReaderModeStyleViewControllerDelegate {
    func readerModeStyleViewController(_ readerModeStyleViewController: ReaderModeStyleViewController,
                                           didConfigureStyle style: ReaderModeStyle,
                                           isUsingUserDefinedColor: Bool)
}

```

Comment (nbhasin2) [reply Client/Frontend/Reader/ReaderModeStyleViewController.swift]: We can then modify at other places like: 

`self.readerModeStyleViewController(ReaderModeStyleViewController(), didConfigureStyle: readerModeStyle, isUsingUserDefinedColor: false)`

**Comment by nbhasin2** [comment]
Fyi @nick130586 I also had some trouble running your code after you merged master. It did work before so I tried it in my branch with some refactoring. Thought I'll let you know and see if below helps :) 

**Original commit:** 
https://github.com/nbhasin2/firefox-ios/commit/ab7e7e2981247e040bf54d007effcfde201802ef
**Refactored commit:** 
https://github.com/nbhasin2/firefox-ios/commit/25c7f8be957715c9d234291d0e77c0a170b64e8c

File: Client/Frontend/Reader/ReaderMode.swift (hunk 2 above)
Comment (nbhasin2) [reply Client/Frontend/Reader/ReaderMode.swift]:
```Swift 
//After refactoring we'll also change reader mode theme to use  `ReaderModeTheme.preferredTheme()`

readerModeStyle.theme = ReaderModeTheme.preferredTheme()
```

**Comment by nick130586** [comment]
Pushed an update to address code review feedback; rebased off master
