### PR TITLE
Bugfix FXIOS-29068 [Telemetry] Fix missing homepage.viewed telemetry when opening new tab from toolbar.

### LINKED ISSUE #29068: Missing homepage impression telemetry when creating a new tab from the toolbar
`homepage.viewed` telemetry gets is missing when using the “+” toolbar button to create a new tab, which lands you on the homepage

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXIOS-13364)

### PR DESCRIPTION
**Pull request by Rinwaoluwa**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-13364)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/29068)

## :bulb: Description
Fixes missing `homepage.viewed` telemetry events when users create a new tab using the "+" toolbar button while viewing a regular webpage.

Closes #29068

## Problem
The `updateEmbeddedContent` method contained a guard condition that prevented the `didSelectedTabChangeToHomepage` action from being dispatched unless the **previous** tab was also a homepage:

```swift
guard previousTab?.isFxHomeTab ?? false else { return }
```
Refactored the guard condition that prevented the didSelectedTabChangeToHomepage action from firing if the user navigated to the homepage from a non-homepage tab. This change ensures that the homepage.viewed telemetry impression is correctly recorded when a new tab is created via the "+" toolbar button, regardless of the previous tab's content.

## :movie_camera: Demos

| Before | After |
| - | - |
|  |  |
|  |  |
|  |  |

<details>
<summary>Demo</summary>

</details>

## :pencil: Checklist
- [X] I filled in the ticket numbers and a description of my work
- [X] I updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] I ensured unit tests pass and wrote tests for new code
- [ ] If working on UI, I checked and implemented accessibility (Dynamic Text and VoiceOver)
- [ ] If adding telemetry, I read the [data stewardship requirements](https://github.com/mozilla-mobile/firefox-ios/wiki/Adding-Glean-Telemetry-Events) and will request a data review
- [ ] If adding or modifying strings, I read the [guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/How-to-add-and-modify-Strings) and will request a string review from l10n
- [X] If needed, I updated documentation and added comments to complex code

### CODE REVIEW

**Comment by Rinwaoluwa** [comment]
Hiii @cyndichin  😊 could you please take a look at this once you’re done reviewing my other PR? Thanks so much! 🙏

**Comment by Rinwaoluwa** [comment]
hi @PARAIPAN9 😊 can you please take a look at this ?

**Comment by PARAIPAN9** [comment]
How did I miss this. Sorry @Rinwaoluwa for taking too long to review your PR. I'll let @cyndichin review it as it seems she has some context around this issue.

**Comment by cyndichin** [comment]
@Rinwaoluwa apologies for the delay, I fell ill towards the end of last week. Taking a look now!

**Comment by cyndichin** [comment]
@Rinwaoluwa thanks for looking into this, the issue is that if we remove that guard then we get the issue that the homepage viewed telemetry will be reported twice in other cases such as launching the app. Here are some cases that we want to make sure are also reporting properly with any fix that we add:

- Open a new tab from the tab tray
- Switch from private to normal via mask (ipad)
- Open a new tab from long press on tab tray
- Switch from web page to homepage via homepage button
- Open new tab from new menu
- Open from address bar when on webpage
- Launch

**Comment by cyndichin** [comment]
also tagging @Foxbolts as he is the reference person for this ticket

File: firefox-ios/Client/Frontend/Browser/BrowserViewController/Views/BrowserViewController.swift [hunk 1]
```diff
@@ -4662,7 +4662,7 @@ extension BrowserViewController: TabManagerDelegate {
     private func updateEmbeddedContent(isHomeTab: Bool, with webView: WKWebView, previousTab: Tab?) {
         if isHomeTab {
             updateInContentHomePanel(webView.url)
-            guard previousTab?.isFxHomeTab ?? false else { return }
+            guard previousTab != nil else { return }
```
Comment (cyndichin) [inline firefox-ios/Client/Frontend/Browser/BrowserViewController/Views/BrowserViewController.swift:4692]: Can we also update the comment for `previousTab` since we are no longer checking for opening a new homepage?

**Comment by Foxbolts** [comment]
> Open a new tab from the tab tray ⚠️ - sometimes trigger twice, also if we select a webview the call gets triggered.

Hey @cyndichin, this case is covered in [FXIOS-13363: Duplicate homepage impression telemetry](https://mozilla-hub.atlassian.net/browse/FXIOS-13363), so maybe we can add on to that. 

There are a lot of cases here, and it is not totally clear to me where we do and do not expect `homepage.viewed` telemetry; I think we might need input from Product on some of the others.

File: firefox-ios/Client/Frontend/Browser/BrowserViewController/Views/BrowserViewController.swift (hunk 1 above)
Comment (Rinwaoluwa) [reply firefox-ios/Client/Frontend/Browser/BrowserViewController/Views/BrowserViewController.swift:4692]: Already Done ✅. Thank you for taking the time to review!

**Comment by cyndichin** [comment]
> > Open a new tab from the tab tray ⚠️ - sometimes trigger twice, also if we select a webview the call gets triggered.
> 
> Hey @cyndichin, this case is covered in [FXIOS-13363: Duplicate homepage impression telemetry](https://mozilla-hub.atlassian.net/browse/FXIOS-13363), so maybe we can add on to that.
> 
> There are a lot of cases here, and it is not totally clear to me where we do and do not expect `homepage.viewed` telemetry; I think we might need input from Product on some of the others.

Thanks for the context @Foxbolts! I'll add more details to that ticket eventually. Ping me if there's a rush to tackle this. We did an audit with John previously, but might be good idea to revisit this to see what's valuable. Should we keep extra metadata on how users are viewing the homepage from all these cases as well?

Also I think I want to noodle a bit on finding a way to test or validate these calls without having to do it manually.
