### PR TITLE
Fix #5213 - Desktop mode requires reloading without cache

### LINKED ISSUE #5213: Request Desktop Site Not Remembered
Logged via : https://bugzilla.mozilla.org/show_bug.cgi?id=1562450

Steps to reproduce:

Go to slickdeals.net (get mobile version)
Request Desktop Site (get desktop version)
Close tab
Go to slickdeals.net (get mobile version)

Actual results:

The request desktop site is forgotten between visits.

Expected results:

Per https://support.mozilla.org/en-US/kb/viewing-desktop-sites-firefox-ios:

"When you request a site in desktop view one time, Firefox will always show that site in desktop view every time you visit until you switch back to mobile."

This is how it used to work. Broke in past couple months.

### PR DESCRIPTION
**Pull request by garvankeeley**

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WebViewDelegates.swift [hunk 1]
```diff
@@ -269,18 +269,17 @@ extension BrowserViewController: WKNavigationDelegate {
...
             if let host = url.host, navigationAction.targetFrame?.isMainFrame ?? false {
                 tab.desktopSite = Tab.DesktopSites.hostList.contains(host)
                 if !tab.desktopSite, tab.isPrivate {
                     // Private mode has an additional memory-only list to check.
                     tab.desktopSite = Tab.DesktopSites.privateModeHostList.contains(host)
                 }
+
+                let requestUA = navigationAction.request.value(forHTTPHeaderField: "User-Agent") ?? ""
+                if UserAgent.isDesktop(ua: requestUA) != tab.desktopSite {
+                    webView.load(URLRequest(url: url, cachePolicy: .reloadIgnoringLocalCacheData, timeoutInterval: 60) as URLRequest)
```
Comment (garvankeeley) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WebViewDelegates.swift]: this `load` seems to work well with the decisionHandler(.allow), which is suprising to me. The history stack stays correct.

File: Client/Frontend/Browser/Tab.swift [hunk 2]
```diff
@@ -450,8 +450,7 @@ class Tab: NSObject {
 
     func reload() {
         let userAgent: String? = desktopSite ? UserAgent.desktopUserAgent() : nil
-        if (userAgent ?? "") != webView?.customUserAgent,
-           let currentItem = webView?.backForwardList.currentItem {
+        if (userAgent ?? "") != webView?.customUserAgent, let currentItem = webView?.backForwardList.currentItem {
```
Comment (garvankeeley) [inline Client/Frontend/Browser/Tab.swift]: Just a code reformatting here.
