### PR TITLE
Fix #6524: SentryDSN not set properly in app extensions

### LINKED ISSUE #6524: Sentry not working from app extensions
Sentry logging is not working from the notification service extension (I know because we are logging non-fatal issues here, and these are not being reported in the web interface).
We need to figure out a system of getting logging information from these extensions.

### PR DESCRIPTION
**Pull request by garvankeeley**

### CODE REVIEW

File: Shared/SentryIntegration.swift [hunk 1]
```diff
@@ -48,6 +48,16 @@ public class Sentry {
         }
 
         guard let dsn = Bundle.main.object(forInfoDictionaryKey: SentryDSNKey) as? String, !dsn.isEmpty else {
+        var bundle = Bundle.main
+        if bundle.bundleURL.pathExtension == "appex" {
+            // Peel off two directory levels
```
Comment (nbhasin2) [inline Shared/SentryIntegration.swift:53]: nit: comment //Peel off two directory levels - MY_APP.app/PlugIns/MY_APP_EXTENSION.appex
