### PR TITLE
Fix #5424 - Hide Images toggle is not visible

### LINKED ISSUE #5424: Hide Images toggle is not visible
Build: 19.0(16042)
Device: iPhone Xr
iOS: 12.2

Steps to reproduce;
1. Switch to Dark theme
2. Open the hamburger menu

Actual results:
- The Hide Images toggle is not visible. The background color of the menu seems to be darker than previous versions.

image

### PR DESCRIPTION
**Pull request by andreap007**
Menu switch was almost invisible in dark mode: https://monosnap.com/file/qudIm3mUEVTdkGR0IbOIGhtrYnQHn6

I have put a slightly different colour without alpha value: https://monosnap.com/file/KyndF0gCQOEziuF6BWuHIkHodDjyff

I have tested in incognito mode and with different accessibility settings, as mentioned in a related bug.

P.S. link for the old PR https://github.com/mozilla-mobile/firefox-ios/pull/5930
I was figuring out how to clean commit history mess and ended up removing the necessary branch.

### CODE REVIEW

File: Client/Frontend/Widgets/PhotonActionSheet/PhotonActionSheetCell.swift [hunk 1]
```diff
@@ -91,8 +91,7 @@ class PhotonActionSheetCell: UITableViewCell {
         func setOn(_ on: Bool) {
             foreground.image = on ? UIImage(named: "menu-customswitch-on") : UIImage(named: "menu-customswitch-off")
             mainView.accessibilityIdentifier = on ? "enabled" : "disabled"
-            mainView.tintColor = on ? UIColor.theme.general.controlTint : UIColor.Photon.Grey90A40
-        }
+            mainView.tintColor = on ? UIColor.theme.general.controlTint : UIColor.Photon.theme.general.switchToggle }
```
Comment (dnarcese) [inline Client/Frontend/Widgets/PhotonActionSheet/PhotonActionSheetCell.swift]: One change, the colour is accessed as `UIColor.theme.general.switchToggle` (no `Photon` needed).
