### PR TITLE
Bugfix FXIOS-13891 [WebKit] Avoid termination on cross-origin blank tab opener

### LINKED ISSUE #21030: PayPal Checkout Button Opens in Same Frame on Firefox iOS
## Steps to reproduce
When clicking on the PayPal checkout button, a new tab is correctly opened in all mobile and desktop browsers. However, on Firefox for iOS, the checkout process opens within the same frame instead of a new tab.

Go to one of the demo pages below and select PayPal payment method then click on the PayPal button

https://demo.paypal.com/us/demo/go_platform/pcRestServerV2/home
https://www.mystoredemo.io/#/checkout

### Expected behavior
It should be opened in a new tab similar to the other browsers.

### Actual behavior
It opens within the same frame. This behavior is causing display issues especially if the button is clicked from in iFrame.

### Device & build information
* Device: iphone 11 OS 17.4.1
* Firefox version 127.0
image

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9496)

### LINKED ISSUE #21314: On online stores, Paypal connection fails with blank screen
## Steps to reproduce
An example easy to see: connect to bienmanger.com, select a product, try to pay with Paypal. Blank screen. (Try the same with Safari (IOS) and it works normally).

### Expected behavior
Obviously, reaching the Paypal servers. 

### Actual behavior
A new tab is created for connecting to Paypal. The URL bar shows "about: blank" and the page is empty.

### Device & build information
* Device:  iPad Pro (11-inch) (2nd generation).  iPadOS Version 17.5.1.
* Build version: iPadOS 17.5.1 (21F90)
* First seen version: sorry, cannot say first seen. What I do know is it always behaved that way.

### Notes
Attachments: 
IMG!UNITO-UNDERSCORE!0125
IMG!UNITO-UNDERSCORE!0123

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9699)

### PR DESCRIPTION
**Pull request by janbrasna**
## :scroll: Tickets
Jira ticket FXIOS-13891
GitHub issue #30098

## :bulb: Description

Workaround to safely touch document object from userscript JS on blank tabs originating in cross-frame cross-origin context, that would terminate/reload the WebKit content process (instead of e.g. empty results or SecurityError exception) — effectively losing any opener context leaving unowned broken orphaned empty tabs behind.

This is predominantly affecting PayPal popup windows.
(Resolves #21030 and also fixes #21314)

Some WebKit references linked from https://github.com/mozilla-mobile/firefox-ios/issues/30098#issuecomment-4043620895 details.

## :movie_camera: Demos

https://github.com/user-attachments/assets/8cf3c468-fcbc-4503-a834-54e37d7493f3

This shows the SDK v6 deeper in the checkout (new windows both on iPhone and iPad), and further in the video also previous SDK v5 used right in the cart step (that will leave that decision to PayPal: currently only iPad, or more precisely, "desktop mode" gets new windows), so both mobile mode and desktop mode are captured in the video.

(When testing locally, don't forget to `npm run build` — or re-bootstrap basically.)

NB: Running this in Simulator you'd see a `com.apple.WebKit.GPU` crash after successfully navigating to the PayPal popup — that's expected (Simulator is missing Secure Enclave abilities and its mocking capabilities have unhandled rough edges from their side — so the trampoline crashes up to the host system) … and is actually a "good sign" that the popup navigation worked, because the trust action comes from within PayPal, so the navigation must have succeeded at that point yay!

## :pencil: Checklist
- [x] I filled in the ticket numbers and a description of my work
- [x] I updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] I ensured unit tests pass and wrote tests for new code
- [x] If needed, I updated documentation and added comments to complex code

### CODE REVIEW

**Comment by issammani** [comment]
> When running locally don't forget to npm run build (and maybe clean build if that doesn't appear being picked up)

I added `npm run dev` a while back. It starts a watcher that rebundles the JS on file save. It's very helpful when developing JS stuff.

File: firefox-ios/Client/Frontend/UserContent/UserScripts/AllFrames/AtDocumentEnd/Ads.js [hunk 1]
```diff
@@ -44,8 +44,23 @@ function getLinks() {
...
+    // FXIOS-13891: WebKit process crashes on cross-origin cookie operation on about:blank tabs
+    if (window.location.protocol == "about:" && window.opener && window.opener.parent != window.opener) {
+        let frameParent = window.opener.parent;
+        // Positively catch the SecurityError on the conditional as a way to not touch the cookie inside
+        try {
+            if (frameParent.location.origin == window.opener.location.origin) {
+                cookiesList = document.cookie.split("; ");
+            }
+        } catch {
+            cookiesList = [""];
```
Comment (janbrasna) [inline firefox-ios/Client/Frontend/UserContent/UserScripts/AllFrames/AtDocumentEnd/Ads.js]: NB: To keep it a little more _DRY_ I'm not adding another `else` here with the same all over again — with the idea that: the conditional is either secure thus truthy… or throws (at least in WebKit as of 2022+) — so I'm avoiding another _else empty list_ for sanity, given it will be empty to start with.

(I'm adding it deliberately in the `catch` for readability to explicitly make the code scream it's aware of the SecurityError and actually making a meaningful use of it — but the catch could be just empty for starters as this being a single item empty string array is just a convenience to match the behavior of empty cookie jar otherwise /compared to empty array completely meaning it couldn't have been read at all/…)

File: firefox-ios/Client/Frontend/UserContent/UserScripts/AllFrames/AtDocumentEnd/Ads.js [hunk 2]
```diff
@@ -44,8 +44,23 @@ function getLinks() {
  * @return {Array<{name: string, value: string}>} containing all cookies.
  */
 function getCookies() {
-    let cookiesList = document.cookie.split("; ");
     let result = [];
+    let cookiesList = [];
```
Comment (issammani) [inline firefox-ios/Client/Frontend/UserContent/UserScripts/AllFrames/AtDocumentEnd/Ads.js]: Just a couple of nits to make the code read better.

Let's keep `getCookies` as is and have it call a `safeCookiesList` that internally calls `document.cookie.split("; ")`. Let's also extract the checks into named variables so it's clear what they're checking, since not everyone on the team is familiar with these DOM APIs. I want them to at least have a sense of what the code is doing at a glance. For example:

```js
const isOpenedByIframe = window.opener && window.opener.parent != window.opener;
const isSameOrigin = frameParent.location.origin == window.opener.location.origin;
```

Comment (janbrasna) [reply firefox-ios/Client/Frontend/UserContent/UserScripts/AllFrames/AtDocumentEnd/Ads.js]: Great suggestions how to put the implicit reasoning right into naming the conditions! 🎸 

Not everything will be feasible thanks to the exact point I need the evaluation actually raise the SecurityException — but I'll try to get as close to that as possible.

The core MRE+STR are currently verified as fixed on the first pass, but I'll only move it out of draft once the actual code block is self-explanatory and well-documented for the next person stumbling upon its location.

Comment (janbrasna) [reply firefox-ios/Client/Frontend/UserContent/UserScripts/AllFrames/AtDocumentEnd/Ads.js]: OK given I'm pretty positive the code might go away completely as eventually unused, I'm not adding too much complexity for now. Ideally this would just end up removed after all on the JS side not having a consumer in the native code — will follow up with a ticket separately for broader investigation.

@issammani Is this something more along the lines you had in mind for self-explanatory conditions?
(cc @yoanarios for opinion: Would these changes help understand the context for anyone else trying to reason about this code? Thank you.)

Comment (issammani) [reply firefox-ios/Client/Frontend/UserContent/UserScripts/AllFrames/AtDocumentEnd/Ads.js]: Yes thanks for making the change ❤️

**Comment by lmarceau** [comment]
Great work @janbrasna 🎉 I'll merge this in since all checks are green. I'll also request QA on the tickets related to this work. Thank you 🙏
