### PR TITLE
FXIOS-1266 ⁃ Fixes chron tabs title overflow #7703 and empty screenshot issue #7673

### LINKED ISSUE #7673: FXIOS-1233 ⁃ [Chron tabs] Empty screenshot shows up in chron tabs for last week
image

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1233)

### LINKED ISSUE #7703: FXIOS-1264 ⁃ [Chron tabs] Title overflow: long title
image

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1264)

### PR DESCRIPTION
**Pull request by nbhasin2**
Fixes #7673 ⁃ [Chron tabs] Empty screenshot shows up in chron tabs for last week
Fixes #7703 ⁃ [Chron tabs] Title overflow when quickly switching between private and regular tabs

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1266)

### CODE REVIEW

File: Client/Frontend/Browser/Tabs/TabTableViewCell.swift [hunk 1]
```diff
@@ -37,23 +49,32 @@ class TabTableViewCell: UITableViewCell, Themeable {
...
-        applyTheme()
+    }
+    
+    // Helper method to remake title constraint
+    func remakeTitleConstraint() {
+        guard let websiteTitle = websiteTitle, let screenshotView = screenshotView, let urlLabel = urlLabel else { return }
+        
+        websiteTitle.numberOfLines = 2
+        websiteTitle.snp.remakeConstraints { make in
+             make.leading.equalTo(screenshotView.snp.trailing).offset(TabTrayV2ControllerUX.screenshotMarginLeftRight)
```
Comment (dnarcese) [inline Client/Frontend/Browser/Tabs/TabTableViewCell.swift:73]: nit: there is an extra space here

**Review by dnarcese — CHANGES_REQUESTED** [review]
The alignment in the labels is off now 🤔
image

File: Client/Frontend/Browser/Tabs/TabTableViewCell.swift [hunk 2]
```diff
@@ -38,22 +50,32 @@ class TabTableViewCell: UITableViewCell, Themeable {
         }
         
         websiteTitle.numberOfLines = 2
```
Comment (nbhasin2) [inline Client/Frontend/Browser/Tabs/TabTableViewCell.swift:52]: image

This will fix constraint issue for 2 lines

**Review by dnarcese — APPROVED** [review]
