### PR TITLE
Bugfix #9724 [v96]: Fix shortcut tile layout for portrait and landscape

### LINKED ISSUE #9724: [iPad] Website shortcuts title overlap
## Steps to reproduce
1. Launch Firefox in portrait
2. Log in to FxA that contain website shortcuts with long titles
### Expected behavior
- Website shortcuts title should  not overlap
### Actual behavior
- The websites shortcut titles overlap
### Device & build information
* Device: iPad Air 2 2nd generation (15.1)
* Build version: 96.0 (7278)
### Notes
- Reproducible on devices with display of 9.7 inch and lower.
Attachments: 
screenshot

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3582)

### PR DESCRIPTION
**Pull request by nishant2718**
# Overview

Fixes #9724. 

## Testing
Follow the STR in #9724.

### CODE REVIEW

File: Client/Frontend/Home/FirefoxHomeTopSitesCell.swift [hunk 1]
```diff
@@ -422,7 +422,7 @@ class ASHorizontalScrollCellManager: NSObject, UICollectionViewDelegate, UIColle
         // On iPad
         // The number of items in a row is equal to the number of highlights in a row * 2
         var numItems = Int(FirefoxHomeUX.numberOfItemsPerRowForSizeClassIpad[traits.horizontalSizeClass])
-        if UIWindow.isLandscape || (traits.horizontalSizeClass == .compact && isLandscape) {
+        if UIWindow.isPortrait || (traits.horizontalSizeClass == .compact && isLandscape) {
```
Comment (nbhasin2) [inline Client/Frontend/Home/FirefoxHomeTopSitesCell.swift:425]: It would be nice to add a before ans after pic for visual reference.

**Review by nbhasin2 — APPROVED** [review]

**Comment by nishant2718** [comment]
The number of tiles with the bug is 8 in portrait, and 6 in landscape. After the bug fix, this is switched to 6 in portrait and 8 in landscape (as it was originally). 

Here are images for reference. 

IMG_0006

IMG_0005
