### PR TITLE
Fix #8214 - Fix testTopSitesRemoveAllExceptPinnedClearPrivateData

### LINKED ISSUE #8214: FXIOS-1642 ⁃ [XCUITests] Update the rest of the XCUITests in the Fennec_XCUITests test plan after latest changes in the app
Tests for the Smoketest plan are already fixed, but we need to fix also all the tests for the full test plan after [PR ](https://github.com/mozilla-mobile/firefox-ios/commit/1c4cb34a6366e27cee8f2d31293f0793832db34e)landed.

Now the app starts with the URL Bar focused and that changes the way all tests start.
Using a new action in the FxScreenGraph would help to manage this by canceling the open url bar and going to homescreen so that test starts as before.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1642)

### PR DESCRIPTION
**Pull request by SimonBasca**
- Fix testTopSitesRemoveAllExceptPinnedClearPrivateData

### CODE REVIEW

File: XCUITests/FxScreenGraph.swift [hunk 1]
```diff
@@ -478,6 +479,11 @@ func createScreenGraph(for test: XCTestCase, with app: XCUIApplication) -> MMScr
             }
         }
         
+        screenState.gesture(forAction: Action.CloseURLBarOpen, transitionTo: HomePanelsScreen) {_ in
+            sleep(1)
+            app.buttons["urlBar-cancel"].tap()
+        }
+
```
Comment (SimonBasca) [inline XCUITests/FxScreenGraph.swift:486]: I've added the `Action.CloseURLBarOpen` here because when I tried to add it to `map.addScreenState(URLBarOpen) ` it failed to close the URL Bar focus.

File: XCUITests/ActivityStreamTest.swift [hunk 2]
```diff
@@ -143,12 +143,16 @@ class ActivityStreamTest: BaseTestCase {
...
         navigator.performAction(Action.AcceptRemovingAllTabs)
+        navigator.performAction(Action.CloseURLBarOpen)
         navigator.performAction(Action.OpenNewTabFromTabTray)
 
         waitForExistence(app.collectionViews.cells[newTopSite["topSiteLabel"]!])
         XCTAssertTrue(app.collectionViews.cells[newTopSite["topSiteLabel"]!].exists)
         checkNumberOfExpectedTopSites(numberOfExpectedTopSites: 6)
 
+        navigator.goto(NewTabScreen)
+        app.buttons["urlBar-cancel"].tap()
```
[the remark this answers is not in the document]
Comment (isabelrios) [reply XCUITests/ActivityStreamTest.swift:154]: @SimonBasca I see the problem. It tries to go to settings from a new tab, so you can fix that by adding these two lines in L153 and 154 instead of those two you have: 
```
navigator.performAction(Action.CloseURLBarOpen)
navigator.nowAt(NewTabScreen)
```
to kind of tell the app that you are already in a new tab and you only need to open settings. I tried that locally and it seems to be working

File: XCUITests/FxScreenGraph.swift (hunk 1 above)
Comment (isabelrios) [reply XCUITests/FxScreenGraph.swift:486]: Sounds good! it may be a better place than the other one.. but I will try to remove the sleep from there, it will make tests slower... I would suggest to add a `waitForExistence(app.buttons["urlBar-cancel"], timeout: 5) ` in the tests before calling the new action defined:
`navigator.performAction(Action.CloseURLBarOpen)`

that way you will wait for that element if it is needed but you won't if it is there already... Please let me know if that works

**Review by isabelrios — APPROVED** [review]
LGTM, I would like to land this asap so that we can go ahead a fix all the other test suites using the action created to close the url bar.
I have re-run the tests, once they pass feel free to land it

**Comment by SimonBasca** [comment]
@isabelrios , I'm still having issues with merging PR. Please merge this.

**Comment by isabelrios** [comment]
> @isabelrios , I'm still having issues with merging PR. Please merge this.

Yeah :( I saw a lot of test failures that did not fail before, let me re-trigger and I will merge after that

**Comment by isabelrios** [comment]
All tests passed after a re-try, merging...
