### PR TITLE
Fix #5781 - [iPad] Tabs tray layout is not correct when entering split screen

### LINKED ISSUE #5781: [iPad] Tabs tray layout is not correct when entering split screen
Build 20.2(16690)
Device iPad Air 3
iOS 12.4

Steps to reproduce:
1. Open a few tabs
2. Open Tabs Tray
3. Change the view to split screen

Actual results:
- The tabs tray layout is not correct. After focusing on a tab and opening tabs tray again, the layout will be correct.

### PR DESCRIPTION
**Pull request by nbhasin2**
Tabs collection view layout wasn't being refreshed when the the app entered split screen mode. Now when the user changes the width while in split screen mode the code changes accommodates for refreshing the collection view layout. 

- Run Firefox on iPad 
- Open many tabs (Eg. 10)
- Go to the tabs collection (Tray) 
- Now add another app Eg. Messages as a split screen app 
- It should show the proper layout

image

### CODE REVIEW

File: Client/Frontend/Browser/TabTrayController.swift [hunk 1]
```diff
@@ -48,7 +48,7 @@ class TabTrayController: UIViewController {
     var collectionView: UICollectionView!
 
     let statusBarBG = UIView()
-
+
```
Comment (garvankeeley) [inline Client/Frontend/Browser/TabTrayController.swift]: nit: spurious whitespace change
