### PR TITLE
Fix #6676 - Show tour for an older user

### LINKED ISSUE #6676: [Regression] Open tour  from settings is not working on Beta builds
## Steps to reproduce
Go to Settings  ->  open tour
### Expected behavior
Onboarding screens are shown
### Actual behavior
Nothing happens, the onboarding is not open, settings is closed and user is in the page where settings was open
### Device & build information
* Build version: Beta

### PR DESCRIPTION
**Pull request by nbhasin2**

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -2053,12 +2053,7 @@ extension BrowserViewController {
     }
     
     private func showProperIntroVC() {
-        // The onboarding screen type should always exist after
-        // the screen is presented for the 1st time
-        guard let onboardingScreenType = self.onboardingUserResearch?.onboardingScreenType else {
-            return
-        }
-        let introViewController = IntroViewControllerV2(onboardingType: onboardingScreenType)
+        let introViewController = IntroViewControllerV2()
```
Comment (nbhasin2) [inline Client/Frontend/Browser/BrowserViewController.swift:2056]: The viewmodel for introview controller should handle nil case and we no longer need to guard.

File: Client/Frontend/Intro/IntroViewModelV2.swift [hunk 2]
```diff
@@ -27,6 +27,10 @@ class IntroViewModelV2 {
     // Initializer
     init() {
         onboardingResearch = OnboardingUserResearch()
-        screenType = onboardingResearch?.onboardingScreenType
+        // Case: Older user who has updated to a newer version and is not a first time user
+        // When user updates from a version of app which didn't have the
+        // user research onboarding screen type and is trying to Always Show the screen
+        // from Show Tour, we default to our .version1 of the screen
+        screenType = onboardingResearch?.onboardingScreenType ?? .versionV1
```
Comment (nbhasin2) [inline Client/Frontend/Intro/IntroViewModelV2.swift:34]: Instead of adding guard and making checks to the BVC, I have mode the logic to the intro viewmodel where it actually belongs and also addresses the case for an update that older user makes to the new version.
