### PR TITLE
Fix #5669 - XCUITests add test site for popup blocker test

### LINKED ISSUE #5669: [XCUITests] Create a testing site for pop up blocker test
For this [testPopUpBlocker](https://github.com/mozilla-mobile/firefox-ios/blob/master/XCUITests/NavigationTest.swift#L320) we have been using a testing site for long time: http://www.popuptest.com/popuptest1.html

Currently the site is down and so the test failing. 
Instead of looking for an alternative site the option would be to create a testing site that can be launched using the local server.

### PR DESCRIPTION
**Pull request by isabelrios**
PR to fix issue #5669 after having the testing website down for a few days. Let's add a local page to simulate this test and so not relay on external sites

### CODE REVIEW

File: XCUITests/NavigationTest.swift [hunk 1]
```diff
@@ -9,7 +9,7 @@ let website_2 = ["url": "www.example.com", "label": "Example", "value": "example
 
 let urlAddons = "addons.mozilla.org"
 let urlGoogle = "www.google.com"
-let popUpTestUrl = "http://www.popuptest.com/popuptest1.html"
+let popUpTestUrl = path(forTestPage: "test-popup-blocker.html")
```
Comment (npark-mozilla) [inline XCUITests/NavigationTest.swift]: is this a new way to open a local html file?

Comment (isabelrios) [reply XCUITests/NavigationTest.swift]: Well, it is not new, we have been using that for a while now :) but for this test we were using an external site not a local one
