### PR TITLE
Fix #6722, fix #6271: Library panels crashing on text size change

### LINKED ISSUE #6271: App crash when changing text size
STR
1. Open bookmarks panel
2. Go to iOS settings and change the text size
3. Go back to firefox

On Beta 23.1 (17416) the app crashes and the crash reporter dialog pops up.
On Release 23.0, the app _does not_ crash but the bookmark panel closes.

### LINKED ISSUE #6722: BookmarksPanel crashes changing device orientation
STR unknown, from Xcode crash reporter:

```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	0x1938b6a48 __exceptionPreprocess + 220 (NSException.m:199)
1   libobjc.A.dylib               	0x1935ddfa4 objc_exception_throw + 56 (objc-exception.mm:565)
2   CoreFoundation                	0x1937b8e88 +[NSException raise:format:arguments:] + 96 (NSException.m:146)
3   Foundation                    	0x193bee654 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 128 (NSException.m:231)
4   UIKitCore                     	0x197aea824 -[UITableView _endCellAnimationsWithContext:] + 6076 (UITableView.m:2161)
5   UIKitCore                     	0x197b0479c -[UITableView _updateRowsAtIndexPaths:withUpdateAction:rowAnimation:usingPresentationValues:] + 624 (UITableView.m:7595)
6   UIKitCore                     	0x197b04d50 -[UITableView reloadRowsAtIndexPaths:withRowAnimation:] + 212 (UITableView.m:7618)
7   Client                        	0x10223e1a0 SiteTableViewController.applyTheme() + 1380 (SiteTableViewController.swift:202)
8   Client                        	0x10238c250 BookmarksPanel.applyTheme() + 20 (BookmarksPanel.swift:158)
9   Client                        	0x102274600 LibraryViewController.applyTheme() + 396 (LibraryViewController.swift:205)
10  Client                        	0x1023300dc BrowserViewController.applyTheme() + 900 (BrowserViewController.swift:2426)
11  Client                        	0x102330950 @objc BrowserViewController.displayThemeChanged(notification:) + 108 (BrowserViewController.swift:190)
12  CoreFoundation                	0x193812288 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20 (CFNotificationCenter.c:787)
13  CoreFoundation                	0x1938122d0 ___CFXRegistrationPost1_block_invoke + 64 (CFNotificationCenter.c:175)
14  CoreFoundation                	0x193811630 _CFXRegistrationPost1 + 368 (CFNotificationCenter.c:198)
15  CoreFoundation                	0x1938112e8 ___CFXNotificationPost_block_invoke + 104 (CFNotificationCenter.c:1371)
16  CoreFoundation                	0x19378d59c -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1416 (CFXNotificationRegistrarOld.m:168)
17  CoreFoundation                	0x193810c38 _CFXNotificationPost + 1244 (CFNotificationCenter.c:1359)
18  Foundation                    	0x193b6d0c8 -[NSNotificationCenter postNotificationName:object:userInfo:] + 60 (NSNotification.m:576)
19  Client                        	0x1021321cc ThemeManager.current.didset + 356 (ThemeManager.swift:19)
20  Client                        	0x1021322e8 ThemeManager.current.setter + 116 (<compiler-generated>:0)
21  Client                        	0x10233ca74 BrowserViewController.traitCollectionDidChange(_:) + 284 (BrowserViewController.swift:1160)
22  Client                        	0x10233cad4 @objc BrowserViewController.traitCollectionDidChange(_:) + 52 (<compiler-generated>:0)
```

### PR DESCRIPTION
**Pull request by dnarcese**

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -1157,9 +1157,11 @@ class BrowserViewController: UIViewController {
         super.traitCollectionDidChange(previousTraitCollection)
 
         if #available(iOS 13.0, *) {
-            if ThemeManager.instance.systemThemeIsOn {
-                let userInterfaceStyle = traitCollection.userInterfaceStyle
-                ThemeManager.instance.current = userInterfaceStyle == .dark ? DarkTheme() : NormalTheme()
+            if self.traitCollection.hasDifferentColorAppearance(comparedTo: previousTraitCollection) {
```
Comment (garvankeeley) [inline Client/Frontend/Browser/BrowserViewController.swift:1160]: nit: combine the consecutive ifs on 1160 and 1161
