### PR TITLE
Fix #5241 - XCUITests update SUMO page for iPad

### LINKED ISSUE #5241: Sumo support page is different on iPhone and iPad
The website shown on iPad has changed and so the test `testHelpOpensSUMOInTab`is failing.
The one shown on iPhone and on iPad before is:
Screenshot 2019-07-05 at 09 27 19

And the one shown now on iPad is:
Screenshot 2019-07-05 at 09 28 13

Is this the expected one? @farhanpatel if so we will modify the tests for the iPad check. Thanks!

### PR DESCRIPTION
**Pull request by isabelrios**
This PR fixes #5241. The SUMO web site is slightly different for iPad now so the test needs to be updated.

### CODE REVIEW

File: XCUITests/SettingsTest.swift [hunk 1]
```diff
@@ -18,8 +18,12 @@ class SettingsTest: BaseTestCase {
 
         waitUntilPageLoad()
         waitForValueContains(app.textFields["url"], value: "support.mozilla.org")
-        waitForExistence(app.webViews.staticTexts["Firefox for iOS"])
-        XCTAssertTrue(app.webViews.staticTexts["Firefox for iOS"].exists)
+        if iPad() {
+            print (app.debugDescription)
```
Comment (npark-mozilla) [inline XCUITests/SettingsTest.swift]: We still need this?

Comment (isabelrios) [reply XCUITests/SettingsTest.swift]: no, we don't need that...sorry I forgot to remove it and did not realized...Deleted now
