### PR TITLE
Fix #4711 - PDF file shares correctly as file or URL type

### LINKED ISSUE #4711: Sharing PDFs yields local file url
From https://bugzilla.mozilla.org/show_bug.cgi?id=1474850

User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Build ID: 20100101

Steps to reproduce:

1. Open a pdf in Firefox for iOS namely https://www.ucl.ac.uk/~ucfamus/papers/icwsm18.pdf  
2. Use the share functionality from the url bar breadcrumbs
3. Select a messenger app (I used Telegram and Slack) to share the pdf.

Actual results:

A file url ("file:///private/var/mobile/Containers/Data/Application/5746FD85-9747-4707-991A-42407F4A4ABA/tmp/TempDocs/icwsm18.pdf") is sent as a message via the selected messenger.

The recipient is clearly unable to view the file, as it is neither a online reference, nor has she or he downloaded the pdf file.

Expected results:

Either the file or (more intuitively) the online file url as a link shoudl be shared.

### PR DESCRIPTION
**Pull request by garvankeeley**

### CODE REVIEW

File: Client/Frontend/Share/ShareExtensionHelper.swift [hunk 1]
```diff
@@ -11,16 +11,18 @@ private let log = Logger.browserLogger
...
     fileprivate weak var selectedTab: Tab?
 
-    fileprivate let selectedURL: URL
+    fileprivate let selectedURL: URL // for non copy ones
+    fileprivate let fileURL: URL? // for copy type
     fileprivate var onePasswordExtensionItem: NSExtensionItem!
     fileprivate let browserFillIdentifier = "org.appextension.fill-browser-action"
 
-    init(url: URL, tab: Tab?) {
+    init(url: URL, file: URL?, tab: Tab?) {
```
Comment (farhanpatel) [inline Client/Frontend/Share/ShareExtensionHelper.swift]: setting a default value for file `file: URL? = nil` will let us avoid having to add `file:nil` when creating it

File: Client/Frontend/Share/ShareExtensionHelper.swift [hunk 2]
```diff
@@ -55,7 +57,7 @@ class ShareExtensionHelper: NSObject {
 
         activityViewController.completionWithItemsHandler = { activityType, completed, returnedItems, activityError in
             if !completed {
-                completionHandler(completed, activityType.map { $0.rawValue })
+                completionHandler(completed, activityType)
```
Comment (farhanpatel) [inline Client/Frontend/Share/ShareExtensionHelper.swift]: much better than before 👍
