### PR TITLE
FXIOS-1102 ⁃ Fix #7542 - New tab button switches to refresh state when user goes out of the app and comes back

### LINKED ISSUE #7542: FXIOS-1101 ⁃ New Tab Button Switches to Refresh
**Precondition**
In the + button experiment group

**Steps to Reproduce**
1. Open a website in a new tab (VP1)
2. Close and re-open the app OR switch from portrait to landscape (VP2)

**Expected Results**
(VP1&VP2) + button is displayed on the bottom nav bar

**Actual Results**
(VP1) + button is displayed on the bottom nav bar
(VP2) Search icon is displayed in bottom nav bar

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1101)

### PR DESCRIPTION
**Pull request by nbhasin2**
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1102)

### CODE REVIEW

**Review by dnarcese — APPROVED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -259,6 +260,15 @@ class BrowserViewController: UIViewController {
...
             toolbar?.applyTheme()
             toolbar?.addNewTabButton.isHidden = true
+            // This is for showing (+) add tab middle button with A/B test where we need to update both toolbar and url bar when (+) button is enabled.
+            // Urlbar already has reader mode state but we still need to refresh it so that if reader mode is available we don't accidently show reload or stop button in url bar
+            if shouldShowNewTabButton {
+                toolbar?.updateMiddleButtonState(.newTab)
+                let state = urlBar.locationView.readerModeState
+                urlBar.updateReaderModeState(state)
+            } else {
+                toolbar?.updateMiddleButtonState(currentMiddleButtonState ?? .search)
```
Comment (nbhasin2) [inline Client/Frontend/Browser/BrowserViewController.swift:270]: Added this part to make sure when we come from background to foreground that we have proper middle button state. This is also helpful when user rotates their device and will fix - https://github.com/mozilla-mobile/firefox-ios/issues/7167

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 2]
```diff
@@ -920,23 +922,26 @@ class BrowserViewController: UIViewController {
         return false
     }
     
-    func setupMiddleButtonStatus(isLoading: Bool) {
+    func setupMiddleButtonStatus(isLoading: Bool) {
```
Comment (dnarcese) [inline Client/Frontend/Browser/BrowserViewController.swift:925]: nit: extra space

**Review by dnarcese — APPROVED** [review]
