### PR TITLE
Fix #5762: Change re-order control in search engine settings to match…

### LINKED ISSUE #5762: Re-order control in search engine settings is wrong colour
The re-ordering control icon follows the system theme. When the system theme and app theme are different, the icon is not very visible.
IMG_0016

### PR DESCRIPTION
**Pull request by dnarcese**
… app theme.

I also noticed that the code above for hiding the separator line was not working, so I fixed that as well.

### CODE REVIEW

File: Client/Frontend/Settings/SearchSettingsTableViewController.swift [hunk 1]
```diff
@@ -183,13 +183,29 @@ class SearchSettingsTableViewController: ThemedTableViewController {
...
+            for v in cell.subviews where v.classForCoder.description() == "_UITableCellVerticalSeparator" {
                 v.backgroundColor = UIColor.clear
             }
         }
+        
+        // Change re-order control tint color to match app theme
+        for subViewA in cell.subviews {
+            if (subViewA.classForCoder.description() == "UITableViewCellReorderControl") {
+                for subViewB in subViewA.subviews {
+                    if (subViewB.isKind(of: UIImageView.classForCoder())) {
```
Comment (garvankeeley) [inline Client/Frontend/Settings/SearchSettingsTableViewController.swift]: `if let imageView = subviewB as? UIImageView {`

File: Client/Frontend/Settings/SearchSettingsTableViewController.swift [hunk 2]
```diff
@@ -183,13 +183,29 @@ class SearchSettingsTableViewController: ThemedTableViewController {
...
+        // Hide a thin vertical line that iOS renders between the accessoryView and the reordering control.
         if cell.isEditing {
-            for v in cell.subviews where v.frame.width == 1.0 {
+            for v in cell.subviews where v.classForCoder.description() == "_UITableCellVerticalSeparator" {
                 v.backgroundColor = UIColor.clear
             }
         }
+        
+        // Change re-order control tint color to match app theme
+        for subViewA in cell.subviews {
```
Comment (garvankeeley) [inline Client/Frontend/Settings/SearchSettingsTableViewController.swift]: `where subViewA.classForCoder.description() == "UITableViewCellReorderControl"`
