### PR TITLE
Fix #4968 - Google favicon is displayed in tabs tray after visiting google.com and going back to Home

### LINKED ISSUE #4968: Google favicon is displayed in tabs tray after visiting google.com and going back to Home
Build: 17.0 (15191)
Device: iPad Air 2
iOS: 11.4

Preconditions:
- New tab is set to Firefox Home
- Home is set to Firefox Home

Steps to reproduce:
1. Go to google.com
2. Open the hamburger menu 
3. Tap Home button
4. Open tabs tray

Actual results:
- Google favicon is displayed in tabs tray. 

Notes:
- Not a recent regression, reproducible in 16.2.

### PR DESCRIPTION
**Pull request by Logomorph**
Fixes #4968 

**Initial issue:**
Since the Home URL is not a valid URL, loading it would yield no metadata. Because of that, the FaviconHandler would not clear the current favicons

**Summary of change:**
Added a new TabEvent for when there is no metadata available. This notifies the FaviconHandler that there is no metadata and it should clear the favicons

### CODE REVIEW

File: Client/Frontend/Browser/FaviconHandler.swift [hunk 1]
```diff
@@ -104,6 +104,9 @@ extension FaviconHandler: TabEventHandler {
             TabEvent.post(.didLoadFavicon(favicon, with: data), for: tab)
         }
     }
+    func tabMedatadaNotAvailable(_ tab: Tab) {
```
Comment (garvankeeley) [inline Client/Frontend/Browser/FaviconHandler.swift]: `tabMetadataNotAvailable`

File: Client/Helpers/TabEventHandler.swift [hunk 2]
```diff
@@ -52,6 +52,7 @@ import Storage
 protocol TabEventHandler: AnyObject {
     func tab(_ tab: Tab, didChangeURL url: URL)
     func tab(_ tab: Tab, didLoadPageMetadata metadata: PageMetadata)
+    func tabMedatadaNotAvailable(_ tab: Tab)
```
Comment (garvankeeley) [inline Client/Helpers/TabEventHandler.swift]: tabMetadataNotAvailable

File: Client/Helpers/TabEventHandler.swift [hunk 3]
```diff
@@ -66,6 +67,7 @@ protocol TabEventHandler: AnyObject {
 extension TabEventHandler {
     func tab(_ tab: Tab, didChangeURL url: URL) {}
     func tab(_ tab: Tab, didLoadPageMetadata metadata: PageMetadata) {}
+    func tabMedatadaNotAvailable(_ tab: Tab) {}
```
Comment (garvankeeley) [inline Client/Helpers/TabEventHandler.swift]: tabMetadataNotAvailable

File: Client/Helpers/TabEventHandler.swift [hunk 4]
```diff
@@ -113,6 +117,8 @@ enum TabEvent {
             handler.tab(tab, didChangeURL: url)
         case .didLoadPageMetadata(let metadata):
             handler.tab(tab, didLoadPageMetadata: metadata)
+        case .pageMetadataNotAvailable:
+            handler.tabMedatadaNotAvailable(tab)
```
Comment (garvankeeley) [inline Client/Helpers/TabEventHandler.swift]: tabMetadataNotAvailable

**Comment by Logomorph** [comment]
@garvankeeley Fixed :D
