### PR TITLE
FXIOS-1038 ⁃ For #7471 - XCUITests Update tests in general scheme for iOS14

### LINKED ISSUE #7471: FXIOS-1032 ⁃ [XCUITests] Update XCUITest scheme for iOS14
Similarly to what we did to fix the[ Smoketest for iOS14,](https://github.com/mozilla-mobile/firefox-ios/issues/6969) we need to do the same for the general test suite.
There are some test failures due to similar issues on Bitrise, see [logs](https://addons-testing.bitrise.io/builds/c9e9f069dd5ea030/testreport/7e19af96-e170-4e2d-8b8f-e3b398dafb0e/testsuite/0/testcases?status=failed)

Test affected:
		LibraryTestsIphone.testLibraryShortcutHomePage()
		NavigationTest.testLongPressLinkOptionsPrivateMode()
		NavigationTest.testLongPressOnAddressBar()
		NavigationTest.testShareLink()
		NavigationTest.testShareLinkPrivateMode()
		NavigationTest.testWriteToChildPopupTab()
		PhotonActionSheetTest.testSendToDeviceFromPageOptionsMenu()
		PhotonActionSheetTest.testShareOptionIsShown()
		PocketTest.testPocketEnabledByDefault()
		PocketTest.testTapOnMore()
		ReaderViewTest.testMarkAsReadAndUnreadFromReadingList()
		ScreenGraphTest.testChainedActionPerf1()
		SearchTests.testCopyPasteComplete()
		SearchTests.testPromptPresence()
		ThirdPartySearchTest.testCustomEngineFromIncorrectTemplate()
		ThirdPartySearchTest.testCustomSearchEngineAsDefault()
		ThirdPartySearchTest.testCustomSearchEngineDeletion()
		ThirdPartySearchTest.testCustomSearchEngines()

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1032)

### PR DESCRIPTION
**Pull request by isabelrios**
Fixes #7471 there were still some tests not updated to work on iOS14 sims...continue the work here and hopefully finished for now

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1038)

### CODE REVIEW

File: XCUITests/ThirdPartySearchTest.swift [hunk 1]
```diff
@@ -102,7 +96,16 @@ class ThirdPartySearchTest: BaseTestCase {
         XCTAssertFalse(app.scrollViews.otherElements.buttons["Mozilla Engine search"].exists)
     }
     
-    private func DismissSearchScreen() {
+    private func addCustomSearchEngine() {
+        navigator.performAction(Action.AddCustomSearchEngine)
+        waitForExistence(app.buttons["customEngineSaveButton"], timeout: 3)
+        app.buttons["customEngineSaveButton"].tap()
+        // Workaround for iOS14 need to wait for those elements and tap again
+        waitForExistence(app.navigationBars["Add Search Engine"], timeout: 3)
```
Comment (AaronMT) [inline XCUITests/ThirdPartySearchTest.swift:104]: Does this need a wrapper iOS version check?

**Review by AaronMT — APPROVED** [review]

File: XCUITests/ThirdPartySearchTest.swift (hunk 1 above)
Comment (isabelrios) [reply XCUITests/ThirdPartySearchTest.swift:104]: Yup you are totally right, I will fix that and merge, thanks!
