### PR TITLE
FXIOS-1058 ⁃ For #7498 - Sync XCUITest update dependencies

### LINKED ISSUE #7498: FXIOS-1057 ⁃ [XCUI Sync Tests] Update dependencies
`pipenv check ` is failing when executed with this error:
```
Checking installed package safety...
38834: urllib3 <1.25.9 resolved (1.25.8 installed)!
urllib3 before 1.25.9 allows CRLF injection if the attacker controls the HTTP request method, as demonstrated by inserting CR and LF control characters in
```

We need to run `pipenv update` so that the lockfile is updated and so the dependencies to get rid of that error

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1057)

### PR DESCRIPTION
**Pull request by isabelrios**
Fixes #7498

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1058)

### CODE REVIEW

File: XCUITests/IntegrationTests.swift [hunk 1]
```diff
@@ -55,7 +55,7 @@ class IntegrationTests: BaseTestCase {
     private func waitForInitialSyncComplete() {
         navigator.nowAt(BrowserTab)
         navigator.goto(SettingsScreen)
-        waitForExistence(app.tables.staticTexts["Sync Now"], timeout: 15)
+        waitForExistence(app.tables.staticTexts["Sync Now"], timeout: 25)
```
Comment (AaronMT) [inline XCUITests/IntegrationTests.swift:58]: Do we know why recently its needed to bump a timeout incase we need to file a regression?

LGTM

**Review by AaronMT — APPROVED** [review]

File: XCUITests/IntegrationTests.swift (hunk 1 above)
Comment (isabelrios) [reply XCUITests/IntegrationTests.swift:58]: I just increased to be sure the option is there...if it is there, we don't wait until the end...so tests will not be impacted. Thanks!
