### PR TITLE
FXIOS-836 ⁃ For #7249 - XCUITests Fix Authentication Prompt Tests

### LINKED ISSUE #7249: FXIOS-835 ⁃ [XCUITests] Fix Authentication tests
These two tests are failing since there is no need to force the current node (Settings Screen) while using the Graph:
-testPromptPassCodeUponReentry
-testPromptPassCodeUponReentryWithDelay

Fix is simple, just removing that line in each test: L#49 and L#67.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-835)

### PR DESCRIPTION
**Pull request by isabelrios**
Fixes #7249

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-836)

### CODE REVIEW

File: buddybuild_carthage_command.sh [hunk 1]
```diff
@@ -1,3 +1,7 @@
 #!/bin/bash
 carthage version
+
+brew unlink carthage && HOMEBREW_NO_AUTO_UPDATE=1
+brew install --HEAD https://gist.github.com/jdhealy/940eaac689728068c4179dc93269dc06/raw/fef073f74b9046a2377344ddf129a0f247442ffe/carthage.rb
+
```
Comment (AaronMT) [inline buddybuild_carthage_command.sh:6]: Is this temporary?

**Review by AaronMT — APPROVED** [review]

File: buddybuild_carthage_command.sh (hunk 1 above)
Comment (isabelrios) [reply buddybuild_carthage_command.sh:6]: yeah, I'm removing it...just using this PR to try to find a solution to the Carthage issue...only the other two files will be the ones changed in this PR
