### PR TITLE
Fix#6118 - Wrong title of navbarButtonItem on edit mode after rotation

### LINKED ISSUE #6118: Wrong title of navbarButtonItem on edit mode after rotation
Wrong title of navbarButtonItem on edit mode after rotation. Should be text 'Edit' instead of 'Done'.

ezgif com-gif-maker

### PR DESCRIPTION
**Pull request by yusadogru**
Fixes #6118

### CODE REVIEW

File: Client/Frontend/Library/BookmarksPanel.swift [hunk 1]
```diff
@@ -84,18 +84,13 @@ class BookmarksPanel: SiteTableViewController, LibraryPanel {
...
 
         self.doneBarButtonItem = UIBarButtonItem(barButtonSystemItem: .done) { _ in
-            self.tableView.setEditing(false, animated: true)
-            self.navigationItem.leftBarButtonItem = nil
-            self.navigationItem.rightBarButtonItem = self.editBarButtonItem
-            self.setupBackButtonGestureRecognizer()
+            self.disableEditMode()
         }
-
+
```
Comment (dnarcese) [inline Client/Frontend/Library/BookmarksPanel.swift]: nit: remove this extra space
