### PR TITLE
Fix #6615 master branch, added debug path for onboarding screen

### LINKED ISSUE #6615: Latest master a34ba81f524 does not start
## Steps to reproduce
1. Install latest master a34ba81f524 on device
2. Launch master a34ba81f524

### Device & build information
* Device: iPhone Xr
* Build version: a34ba81f524

Screen Shot 2020-05-15 at 2 51 06 PM

### PR DESCRIPTION
**Pull request by nbhasin2**
Basically we are relying on Leanplum to Start and show onboarding screen. In debug mode unless you have Leanplum setup locally to start it will show white screen. 

In this PR I have added Debug option to **Active Compilation Conditions** which allows me to check device is running in debug mode or not.

### CODE REVIEW

File: Client/Application/LeanplumIntegration.swift [hunk 1]
```diff
@@ -281,11 +281,11 @@ class LeanPlumClient {
         return (prefs?.stringForKey(PrefsKeys.KeyMailToOption) ?? "mailto:") == "mailto:"
     }
 
-    private func getSettings() -> LPSettings? {
+    func getSettings() -> LPSettings? {
         let bundle = Bundle.main
-        guard let appId = bundle.object(forInfoDictionaryKey: LPAppIdKey) as? String,
-              let productionKey = bundle.object(forInfoDictionaryKey: LPProductionKeyKey) as? String,
-              let developmentKey = bundle.object(forInfoDictionaryKey: LPDevelopmentKeyKey) as? String else {
+        guard let appId = bundle.object(forInfoDictionaryKey: LPAppIdKey) as? String, !appId.isEmpty,
```
Comment (nbhasin2) [inline Client/Application/LeanplumIntegration.swift:286]: Bundle produced empty string even if it had no value in the plist file.
Hence the additional check for isEmpty

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 2]
```diff
@@ -1995,31 +1995,57 @@ extension BrowserViewController {
...
+            self.onboardingUserResearch?.updateValue(value: lpVariable?.boolValue() ?? true)
+            self.showProperIntroVC()
+        }
+        // Conditon: Leanplum server too slow
+        // We don't want our users to be stuck on Onboarding
+        // Wait 2 second and update the onboarding research variable
+        // with true (True = .variant 1)
+        // Ex. Internet connection is unstable due to which
+        // leanplum isn't loading or taking too much time
+        DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
```
Comment (garvankeeley) [inline Client/Frontend/Browser/BrowserViewController.swift:2032]: Maybe log something to sentry to know how much this is hit?

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 3]
```diff
@@ -2033,6 +2033,7 @@ extension BrowserViewController {
             guard self.onboardingUserResearch?.updatedLPVariables != nil else {
                 return
             }
+            Sentry.shared.send(message: "Failed to fetch A/B test variables from LP")
```
Comment (nbhasin2) [inline Client/Frontend/Browser/BrowserViewController.swift:2036]: @garvankeeley Added a simple message for sentry if we are unable to fetch A/B test variables from LP
