### PR TITLE
Fix shortcut row count not updating after dismissing settings sheet

### LINKED ISSUE #32292: Homepage shortcut row count not updating after dismissing nested settings
**Prerequisite:**

* Have at least 2 rows of homepage shortcuts (>= 5 on iPhone portrait)
* Settings > Homepage > Shortcuts > Rows is set to `2`

**Steps to reproduce:**

* Open Firefox to the homepage
* Go to Settings > Homepage > Shortcuts > Rows
* Set the number of rows to `1`
* Without navigating back, immediately dismiss the settings by swiping down the settings sheet 

**Expected Results:**

* There is 1 row of shortcuts on the homepage 

OR 

* Settings > Homepage > Shortcuts > Rows still displays `2`

**Actual Results:**

* There are still 2 rows of shortcuts on the homepage
* Settings > Homepage > Shortcuts > Rows displays `1`

**Device & Build Information:**

* Device: iPhones and iPads
* Build version: v148

**Screen Recording:**

!Simulator Screen Recording - iPhone 17 - 2026-02-25 at 17.13.29.mov|width=320,alt="Simulator Screen Recording - iPhone 17 - 2026-02-25 at 17.13.29.mov"!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXIOS-14991)

### PR DESCRIPTION
**Pull request by sushanttiwari-14**
##  Tickets
Fixes #32292

##  Description
The homepage shortcut row count was not updating when the settings sheet was dismissed by swiping down.

This change ensures the update is triggered on dismissal, keeping the homepage in sync with user preferences.

## Demos
N/A

##  Checklist
- [x] I filled in the ticket numbers and a description of my work
- [x] I updated the PR name to follow our PR naming guidelines
- [ ] I ensured unit tests pass and wrote tests for new code
- [ ] If working on UI, I checked and implemented accessibility (Dynamic Text and VoiceOver)
- [ ] If adding telemetry, I read the data stewardship requirements
- [ ] If adding or modifying strings, I read the guidelines
- [ ] If needed, I updated documentation and added comments to complex code

### CODE REVIEW

File: firefox-ios/Client/Frontend/Settings/HomepageSettings/TopSitesSettings/TopSitesRowCountSettingsController.swift [hunk 1]
```diff
@@ -62,4 +67,5 @@ class TopSitesRowCountSettingsController: SettingsTableViewController, FeatureFl
             numberOfRows = self.prefs.intForKey(PrefsKeys.NumberOfTopSiteRows) ?? defaultValue
         }
     }
+
```
Comment (Cramsden) [inline firefox-ios/Client/Frontend/Settings/HomepageSettings/TopSitesSettings/TopSitesRowCountSettingsController.swift]: can we delete this extra row?

Comment (sushanttiwari-14) [reply firefox-ios/Client/Frontend/Settings/HomepageSettings/TopSitesSettings/TopSitesRowCountSettingsController.swift]: > can we delete this extra row?
removed the extra line. Thanks

File: firefox-ios/Client/Frontend/Settings/HomepageSettings/TopSitesSettings/TopSitesRowCountSettingsController.swift [hunk 2]
```diff
@@ -23,6 +23,11 @@ class TopSitesRowCountSettingsController: SettingsTableViewController, FeatureFl
         fatalError("init(coder:) has not been implemented")
     }
 
+    override func viewDidDisappear(_ animated: Bool) {
+        super.viewDidDisappear(animated)
+        NotificationCenter.default.post(name: .HomePanelPrefsChanged, object: nil)
```
Comment (Cramsden) [inline firefox-ios/Client/Frontend/Settings/HomepageSettings/TopSitesSettings/TopSitesRowCountSettingsController.swift:28]: We probably do need to fire this on disappear but I think that we would only want to fire it if something has actually changed, not every time.

Comment (sushanttiwari-14) [reply firefox-ios/Client/Frontend/Settings/HomepageSettings/TopSitesSettings/TopSitesRowCountSettingsController.swift]: > We probably do need to fire this on disappear but I think that we would only want to fire it if something has actually changed, not every time.

Tried the dismiss-based notification approach, but it didn’t fully resolve the issue in the swipe-to-dismiss case.

The homepage state is driven by Redux and wasn’t updating with just the pref change, so dispatching `updatedNumberOfRows` ensures the UI reflects the change immediately.

**Review by Cramsden — APPROVED** [review]

**Comment by Cramsden** [comment]
Thank you for this change. Tested out and didn't see any issues!
