### PR TITLE
Fix #5026 - [Regression] Unable to remove a downloaded item, swipe gesture does not work

### LINKED ISSUE #5026: [Regression] Unable to remove a downloaded item, swipe gesture does not work
This is happening on latest master  ed4ac1b. Most likely after this PR #4974 

Steps
-Download a link for example
-Go to Downloads panel
-Try to remove the link by swiping left

Actual
The item is not removed. If you try long pressing, and swiping many times in the end sometimes the Remove menu appears, but is not easy to get it.

Expected
The option to remove an item appears easily and works as expected

I'm wondering if this has changed since is also happening for items added to Reading List and History, but at least there there is the option to remove them by long pressing and selecting Delete. In this case there is no option to remove any downloaded item

### PR DESCRIPTION
**Pull request by justindarc**
This PR fixes the recognition/cancellation of the various pan/swipe gesture recognizers we encounter with table views inside the drawer view.

### CODE REVIEW

File: Client/Frontend/Widgets/DrawerViewController.swift [hunk 1]
```diff
@@ -264,3 +265,17 @@ public class DrawerViewController: UIViewController {
         }
     }
 }
+
+extension DrawerViewController: UIGestureRecognizerDelegate {
+    public func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
+        let description = otherGestureRecognizer.description
+        return description.starts(with: "<_UISwipeActionPanGestureRecognizer:") ||
+            !description.starts(with: "<UIScrollViewPanGestureRecognizer:")
```
Comment (garvankeeley) [inline Client/Frontend/Widgets/DrawerViewController.swift]: would `return !description.starts(with: "<UIScrollViewPanGestureRecognizer:")` work here?
