### PR TITLE
Fix #6474: reconfig FxA in the notification service EVERY time a push arrives

### LINKED ISSUE #6474: "Debug: Error messageIncomplete" is displayed after STR
## Preconditions:
1. Log in to FxA on device A. 
2. Login to FxA on device B.
3. On device A, go to Account Management Page -> Devices & App, and tap "Disconnect" for the current device and "Disconnect" for the current Web Session.
4. Close and re-launch the app on device A
5. Log in to FxA on device A. 
## Steps to reproduce
1. On device B, go to "github.com".
2. Open Page Action Menu.
3. Tap "Send to device"
4. Select device A from the list
### Expected behavior
- Tab should be sent across iOS devices
### Actual behavior
- "Debug: Error messageIncomplete=FirefoxAccountError.unauthorized: Remote server error: 401 110" notification is displayed on device A and the tab is not sent. 
### Device & build information
* Device: 
Device A -> iPhone 7 (13.4.1)
Device B -> iPhone Xr (13.3)
* Build version: 25.0 (17793)

### PR DESCRIPTION
**Pull request by garvankeeley**
The notification service is staying alive and retaining the old FxA state after the account has been disconnected and reconnected.

### CODE REVIEW

File: Account/FxAPushMessageHandler.swift [hunk 1]
```diff
@@ -60,55 +60,57 @@ extension FxAPushMessageHandler {
...
-                events.forEach { event in
-                    switch event {
-                    case .incomingDeviceCommand(let deviceCommand):
-                        switch deviceCommand {
-                            case .tabReceived(_, let tabData):
-                                let title = tabData.last?.title ?? ""
-                                let url = tabData.last?.url ?? ""
-                                let message = PushMessage.commandReceived(tab: ["title": title, "url": url])
-                                deferred.fill(Maybe(success: message))
+            RustFirefoxAccounts.reconfig {
```
Comment (garvankeeley) [inline Account/FxAPushMessageHandler.swift:63]: This line is the actual code change, the rest is an indentation change

**Comment by garvankeeley** [comment]
uplifted to v25.x
