### PR TITLE
Fix #5538 Replacing Brackets in the url with percent encoding

### LINKED ISSUE #5538: URL's with square brackets ([ ]) are not recognised as URL's
Steps to reproduce:

We spotted an issue with an AJAX call not returning anything. We took the AJAX URL and entered it straight into the address bar and it didn't seem to recognise it as a URL and was trying to do a Google search. When we took out the square brackets from the GET parameters it worked.

For example:
https://URL?get_per[]=17

Actual results:
Tried to do a Google search. Didn't seem to recognize it as a URL.

Expected results:
Should have returned the URL

filed via https://bugzilla.mozilla.org/show_bug.cgi?id=1585328

Note: Safari handles this correctly.

### PR DESCRIPTION
**Pull request by marchiore**
Hi, this is my first PR to firefox-ios!

Here I fix the problem when the user submit a bracket (**"["** or **"]"**) in the URL, it causes a  redirect to a google search result, so i replace it with a percent encoding (**"%5B"** and **"%5D"**).

URL Example:

https://stackoverflow.com/search?q=swift+[lint]

### CODE REVIEW

File: Client/Frontend/Browser/URIFixup.swift [hunk 1]
```diff
@@ -54,4 +54,8 @@ class URIFixup {
         }
         return components?.url
     }
+
+    static func replaceBrackets(str: String) -> String {
+        return str.replacingOccurrences(of: "\\[", with: "%5B", options: [.regularExpression]).replacingOccurrences(of: "\\]", with: "%5D", options: [.regularExpression])
```
Comment (garvankeeley) [inline Client/Frontend/Browser/URIFixup.swift]: Can you change this to non-regex?

File: Client/Frontend/Browser/URIFixup.swift [hunk 2]
```diff
@@ -10,8 +10,8 @@ class URIFixup {
         if let url = URL(string: entry), InternalURL.isValid(url: url) {
             return URL(string: entry)
         }
-
-        let trimmed = entry.trimmingCharacters(in: .whitespacesAndNewlines)
+        let replaced = replaceBrackets(str: entry)
+        let trimmed = replaced.trimmingCharacters(in: .whitespacesAndNewlines)
```
Comment (garvankeeley) [inline Client/Frontend/Browser/URIFixup.swift]: Can you move this to after `trimmed.addingPercentEncoding`? 
Then the code becomes `guard var escaped ...` and then `escaped = replaceBrackets...`

File: Client/Frontend/Browser/URIFixup.swift (hunk 1 above)
Comment (marchiore) [reply Client/Frontend/Browser/URIFixup.swift]: Changed!

File: Client/Frontend/Browser/URIFixup.swift (hunk 2 above)
Comment (marchiore) [reply Client/Frontend/Browser/URIFixup.swift]: Done!
