### PR TITLE
Bugfix FX-11735 [A11y] Add VoiceOver position announcements for Stories section (#28257)

### LINKED ISSUE #25589: Thought-Provoking Stories list does not indicate its size and position to VoiceOver
## Steps to reproduce
With a VoiceOver running, navigate to any story under the "Thought-provoking stories" and observe the VO announcement 

### Expected behavior
1. VoiceOver should announce the total length of the list and the position of this specific item

### Actual behavior
1. VoiceOver does not announce any information about the list length and current item's position in it

#### Note: 
Seems that there were changes in the iOS (or VoiceOver) handling of lists - this information is no longer announced by the VoiceOver on iOS-own apps like App Store > Games tabs... Marking it as a "Feature" - it could be an enhancement to indicate for users how long the list is and where they're at. 

If we customize the announcement, the list length is usually announced at the entry of the list (i.e. when VO lands the focus on the first item of the list while navigating forward or on the last item, when navigating backwards). Default behavior was similar to the current Tab announcements (refer to the iOS App store tabs at the bottom of the view) with `1 of 4` and similar information provided for each item

### Device & build information
* Device: iPhone 15 Pro, iOS 18.3.2
* Build version: 9000 (52434)

*# 
*## Notes
Attachments: 
<
!--- Screenshots or screen recordings are very helpful for reproducing|width=200,height=183!
 -->

width=200,height=183

## :information_source:  Reference Person
@cyndichin

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-11735)

### PR DESCRIPTION
**Pull request by yusuphjoluwasen**
- Add localized string for position accessibility hint
- Enhance StoryCell to accept and display position information
- Update HomepageViewController to calculate story positions

Fixes #25589

## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-11735)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/25589)

## :movie_camera: Demos

| Before | After |
| - | - |
|  |  |
|  |  |
|  |  |

<details>
<summary>Demo</summary>

</details>

## :pencil: Checklist
- [x] I filled in the ticket numbers and a description of my work
- [x] I updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] I ensured unit tests pass and wrote tests for new code
- [ ] If working on UI, I checked and implemented accessibility (Dynamic Text and VoiceOver)
- [ ] If adding telemetry, I read the [data stewardship requirements](https://github.com/mozilla-mobile/firefox-ios/wiki/Adding-Glean-Telemetry-Events) and will request a data review
- [ ] If needed, I updated documentation and added comments to complex code
- [ ] If needed, I added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

File: firefox-ios/Shared/Strings.swift [hunk 1]
```diff
@@ -1043,6 +1043,11 @@ extension String {
                     value: "Learn more",
                     comment: "This is the learn more text of the Pocket footer on Firefox Homepage.")
             }
+            public static let PositionAccessibilityHint = MZLocalizedString(
+                key: "FirefoxHomepage.Stories.PositionAccessibilityHint.v143",
+                tableName: "FirefoxHomepage",
+                value: "%@ of %@",
+                comment: "Accessibility hint for story position in the Stories section. %1$@ is current position, %2$@ is total count. Example: '1 of 5'")
```
Comment (adudenamedruby) [inline firefox-ios/Shared/Strings.swift]:
```suggestion
                comment: "On the homepage, in the Stories section, this is the accessibility hint for the position of the current story in the stories stack. The first placeholder is the current position; the second placeholder is the total story count. Example: '1 of 5'")
```

File: firefox-ios/Client/Frontend/Home/Homepage Rebuild/Merino/StoryCell.swift [hunk 2]
```diff
@@ -68,15 +68,25 @@ class StoryCell: UICollectionViewCell, ReusableCell, ThemeApplicable, Blurrable,
...
         titleLabel.numberOfLines = getNumberOfLinesForTitle(isSponsoredStory: !story.shouldHideSponsor)
         accessibilityLabel = story.accessibilityLabel
+        if let position = position, let totalCount = totalCount {
+            accessibilityHint = String(
+                format: .FirefoxHomepage.Pocket.PositionAccessibilityHint,
+                String(position),
+                String(totalCount)
+            )
+        } else {
+            accessibilityHint = nil
```
Comment (adudenamedruby) [inline firefox-ios/Client/Frontend/Home/Homepage Rebuild/Merino/StoryCell.swift]: Do we need to set it to `nil` in an else block, if it's already set to nil from the start and in `prepareForReuse`?

File: firefox-ios/Client/Frontend/Home/Homepage Rebuild/HomepageViewController.swift [hunk 3]
```diff
@@ -552,7 +552,10 @@ final class HomepageViewController: UIViewController,
             }
 
             if let storyCell = storyCell as? StoryCell {
-                storyCell.configure(story: story, theme: currentTheme)
+                let position = indexPath.item + 1
+                let currentSection = dataSource?.snapshot().sectionIdentifiers[indexPath.section] ?? .pocket(.clear)
+                let totalCount = dataSource?.snapshot().numberOfItems(inSection: currentSection) ?? 0
```
Comment (adudenamedruby) [inline firefox-ios/Client/Frontend/Home/Homepage Rebuild/HomepageViewController.swift]: Given that we're unwrapping in the provided function, we don't really need a default value here. Also, we don't want to risk some weird case where it start saying "3 of 0", so an optional is totally fine here.

**Review by adudenamedruby — CHANGES_REQUESTED** [review]
Heya. Thanks for your contribution! Just a couple of clarifying comments, and a change - because our localization peeps prefer a specific format for comments :)

**Comment by yusuphjoluwasen** [comment]
Thanks for you review @adudenamedruby, PR updated

File: firefox-ios/Shared/Strings.swift [hunk 4]
```diff
@@ -1043,6 +1043,11 @@ extension String {
                     value: "Learn more",
                     comment: "This is the learn more text of the Pocket footer on Firefox Homepage.")
             }
+            public static let PositionAccessibilityHint = MZLocalizedString(
+                key: "FirefoxHomepage.Stories.PositionAccessibilityHint.v143",
+                tableName: "FirefoxHomepage",
+                value: "%@ of %@",
+                comment: "On the homepage, in the Stories section, this is the accessibility hint for the position of the current story in the stories stack. The first placeholder is the current position; the second placeholder is the total story count. Example: '1 of 5'")
```
Comment (adudenamedruby) [inline firefox-ios/Shared/Strings.swift]:
```suggestion
                comment: "On the homepage, in the Stories section, this is the accessibility hint for the position of the current story in the stories stack. The first placeholder, %1$@, is the current position; the second placeholder, %2$@, is the total story count. Example: '1 of 5'")
```

ugh, my bad. I forgot about the linter lol let's update this, and then it's good to go in!

**Review by adudenamedruby — CHANGES_REQUESTED** [review]

**Comment by adudenamedruby** [comment]
@Mergify rebase
