### PR TITLE
FXIOS-953 ⁃ For #7380 - XCUITests fix smoketest on iOS14

### LINKED ISSUE #7380: FXIOS-954 ⁃ [XCUITests] Follow up issue to fix smoketest on iOS14
There some other tests failing on Bitrise on iOS14, at least one due to the changes on TP that has to be disabled until updated. 
This issue is to track that work

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-954)

### PR DESCRIPTION
**Pull request by isabelrios**
Fixes #7380

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-953)

### CODE REVIEW

File: XCUITests/AuthenticationTest.swift [hunk 1]
```diff
@@ -41,11 +41,12 @@ class AuthenticationTest: BaseTestCase {
 
         //send app to background, and re-enter
         XCUIDevice.shared.press(.home)
+        sleep(1)
```
Comment (isabelrios) [inline XCUITests/AuthenticationTest.swift:44]: I know this is not good, but how we can verify that the app is loaded again? the problem on Bitrise is that the app does not go completely to background and when it is launched, it is not code blocked... maybe wiating for an element in the springboard will make the trick instead of this...

**Review by SimonBasca — APPROVED** [review]
